version: "3.8"

services:
  alma-vid:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: production
    ports:
      - "80:80"
    container_name: alma-vid-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: mount custom nginx config
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
